[versions]
junitVersion = "1.2.1"
espressoCore = "3.6.1"
composeBom = "2024.11.00" # Sync with libs.versions

[libraries]
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

